// Generated by gencpp from file gnss_driver/GnssRange.msg
// DO NOT EDIT!


#ifndef GNSS_DRIVER_MESSAGE_GNSSRANGE_H
#define GNSS_DRIVER_MESSAGE_GNSSRANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <gnss_driver/RangeInfo.h>

namespace gnss_driver
{
template <class ContainerAllocator>
struct GnssRange_
{
  typedef GnssRange_<ContainerAllocator> Type;

  GnssRange_()
    : header()
    , measurement_time(0.0)
    , ranges()  {
    }
  GnssRange_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , measurement_time(0.0)
    , ranges(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _measurement_time_type;
  _measurement_time_type measurement_time;

   typedef std::vector< ::gnss_driver::RangeInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::gnss_driver::RangeInfo_<ContainerAllocator> >::other >  _ranges_type;
  _ranges_type ranges;





  typedef boost::shared_ptr< ::gnss_driver::GnssRange_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_driver::GnssRange_<ContainerAllocator> const> ConstPtr;

}; // struct GnssRange_

typedef ::gnss_driver::GnssRange_<std::allocator<void> > GnssRange;

typedef boost::shared_ptr< ::gnss_driver::GnssRange > GnssRangePtr;
typedef boost::shared_ptr< ::gnss_driver::GnssRange const> GnssRangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_driver::GnssRange_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_driver::GnssRange_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gnss_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'gnss_driver': ['/home/nthom/Documents/ros/rk_node_tutorial/src/gnss_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gnss_driver::GnssRange_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_driver::GnssRange_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_driver::GnssRange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_driver::GnssRange_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_driver::GnssRange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_driver::GnssRange_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_driver::GnssRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98189513fbb1deb4e990550a5fe42c3d";
  }

  static const char* value(const ::gnss_driver::GnssRange_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98189513fbb1deb4ULL;
  static const uint64_t static_value2 = 0xe990550a5fe42c3dULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_driver::GnssRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_driver/GnssRange";
  }

  static const char* value(const ::gnss_driver::GnssRange_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_driver::GnssRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 measurement_time\n\
RangeInfo[] ranges\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: gnss_driver/RangeInfo\n\
int32 GPS=0\n\
int32 GLONASS=1\n\
int32 SBAS=2\n\
int32 GALILEO=3\n\
int32 BEIDOU=4\n\
int32 QZSS=5\n\
\n\
int32 constellation\n\
int32 prn\n\
\n\
uint32 carrier_frequency\n\
float64 pseudorange\n\
float32 pseudorange_std_dev\n\
float64 carrier_phase\n\
float32 carrier_phase_std_dev\n\
float32 doppler\n\
float32 doppler_std_dev\n\
int32 cno\n\
int32 lock_time\n\
";
  }

  static const char* value(const ::gnss_driver::GnssRange_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_driver::GnssRange_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.measurement_time);
      stream.next(m.ranges);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GnssRange_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_driver::GnssRange_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_driver::GnssRange_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "measurement_time: ";
    Printer<double>::stream(s, indent + "  ", v.measurement_time);
    s << indent << "ranges[]" << std::endl;
    for (size_t i = 0; i < v.ranges.size(); ++i)
    {
      s << indent << "  ranges[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gnss_driver::RangeInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.ranges[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_DRIVER_MESSAGE_GNSSRANGE_H
