// Generated by gencpp from file gnss_driver/Imu.msg
// DO NOT EDIT!


#ifndef GNSS_DRIVER_MESSAGE_IMU_H
#define GNSS_DRIVER_MESSAGE_IMU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <gnss_driver/Pose.h>

namespace gnss_driver
{
template <class ContainerAllocator>
struct Imu_
{
  typedef Imu_<ContainerAllocator> Type;

  Imu_()
    : header()
    , imu()  {
    }
  Imu_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , imu(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::gnss_driver::Pose_<ContainerAllocator>  _imu_type;
  _imu_type imu;





  typedef boost::shared_ptr< ::gnss_driver::Imu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_driver::Imu_<ContainerAllocator> const> ConstPtr;

}; // struct Imu_

typedef ::gnss_driver::Imu_<std::allocator<void> > Imu;

typedef boost::shared_ptr< ::gnss_driver::Imu > ImuPtr;
typedef boost::shared_ptr< ::gnss_driver::Imu const> ImuConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_driver::Imu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_driver::Imu_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gnss_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'gnss_driver': ['/home/nthom/Documents/ros/rk_node_tutorial/src/gnss_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gnss_driver::Imu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_driver::Imu_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_driver::Imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_driver::Imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_driver::Imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_driver::Imu_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_driver::Imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d872bb872d5ed4666e259b29aa20d9c7";
  }

  static const char* value(const ::gnss_driver::Imu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd872bb872d5ed466ULL;
  static const uint64_t static_value2 = 0x6e259b29aa20d9c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_driver::Imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_driver/Imu";
  }

  static const char* value(const ::gnss_driver::Imu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_driver::Imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
Pose imu\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: gnss_driver/Pose\n\
PointENU position\n\
Quaternion orientation\n\
Point3D linear_velocity\n\
Point3D linear_acceleration\n\
Point3D angular_velocity\n\
\n\
float64 heading\n\
Point3D linear_acceleration_vrf\n\
Point3D angular_velocity_vrf\n\
\n\
================================================================================\n\
MSG: gnss_driver/PointENU\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: gnss_driver/Quaternion\n\
float64 qx\n\
float64 qy\n\
float64 qz\n\
float64 qw\n\
\n\
================================================================================\n\
MSG: gnss_driver/Point3D\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::gnss_driver::Imu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_driver::Imu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.imu);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Imu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_driver::Imu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_driver::Imu_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "imu: ";
    s << std::endl;
    Printer< ::gnss_driver::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.imu);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_DRIVER_MESSAGE_IMU_H
