// Generated by gencpp from file gnss_driver/InsStatus.msg
// DO NOT EDIT!


#ifndef GNSS_DRIVER_MESSAGE_INSSTATUS_H
#define GNSS_DRIVER_MESSAGE_INSSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gnss_driver
{
template <class ContainerAllocator>
struct InsStatus_
{
  typedef InsStatus_<ContainerAllocator> Type;

  InsStatus_()
    : header()
    , type(0)  {
    }
  InsStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _type_type;
  _type_type type;



  enum {
    INVALID = 0u,
    CONVERGING = 1u,
    GOOD = 2u,
  };


  typedef boost::shared_ptr< ::gnss_driver::InsStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_driver::InsStatus_<ContainerAllocator> const> ConstPtr;

}; // struct InsStatus_

typedef ::gnss_driver::InsStatus_<std::allocator<void> > InsStatus;

typedef boost::shared_ptr< ::gnss_driver::InsStatus > InsStatusPtr;
typedef boost::shared_ptr< ::gnss_driver::InsStatus const> InsStatusConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_driver::InsStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_driver::InsStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gnss_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'gnss_driver': ['/home/nthom/Documents/ros/rk_node_tutorial/src/gnss_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gnss_driver::InsStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_driver::InsStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_driver::InsStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_driver::InsStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_driver::InsStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_driver::InsStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_driver::InsStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74371ad6e1867e22a3c23379ae98b03d";
  }

  static const char* value(const ::gnss_driver::InsStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74371ad6e1867e22ULL;
  static const uint64_t static_value2 = 0xa3c23379ae98b03dULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_driver::InsStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_driver/InsStatus";
  }

  static const char* value(const ::gnss_driver::InsStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_driver::InsStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint32 INVALID=0\n\
uint32 CONVERGING=1\n\
uint32 GOOD=2\n\
\n\
uint32 type\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::gnss_driver::InsStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_driver::InsStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InsStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_driver::InsStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_driver::InsStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_DRIVER_MESSAGE_INSSTATUS_H
