// Generated by gencpp from file gnss_driver/PointLLH.msg
// DO NOT EDIT!


#ifndef GNSS_DRIVER_MESSAGE_POINTLLH_H
#define GNSS_DRIVER_MESSAGE_POINTLLH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gnss_driver
{
template <class ContainerAllocator>
struct PointLLH_
{
  typedef PointLLH_<ContainerAllocator> Type;

  PointLLH_()
    : lon(0.0)
    , lat(0.0)
    , height(0.0)  {
    }
  PointLLH_(const ContainerAllocator& _alloc)
    : lon(0.0)
    , lat(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef double _lon_type;
  _lon_type lon;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::gnss_driver::PointLLH_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_driver::PointLLH_<ContainerAllocator> const> ConstPtr;

}; // struct PointLLH_

typedef ::gnss_driver::PointLLH_<std::allocator<void> > PointLLH;

typedef boost::shared_ptr< ::gnss_driver::PointLLH > PointLLHPtr;
typedef boost::shared_ptr< ::gnss_driver::PointLLH const> PointLLHConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_driver::PointLLH_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_driver::PointLLH_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gnss_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'gnss_driver': ['/home/nthom/Documents/ros/rk_node_tutorial/src/gnss_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gnss_driver::PointLLH_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_driver::PointLLH_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_driver::PointLLH_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_driver::PointLLH_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_driver::PointLLH_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_driver::PointLLH_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_driver::PointLLH_<ContainerAllocator> >
{
  static const char* value()
  {
    return "360f7307744ede4ebecd668b1e5c39fc";
  }

  static const char* value(const ::gnss_driver::PointLLH_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x360f7307744ede4eULL;
  static const uint64_t static_value2 = 0xbecd668b1e5c39fcULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_driver::PointLLH_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_driver/PointLLH";
  }

  static const char* value(const ::gnss_driver::PointLLH_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_driver::PointLLH_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 lon\n\
float64 lat\n\
float64 height\n\
";
  }

  static const char* value(const ::gnss_driver::PointLLH_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_driver::PointLLH_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lon);
      stream.next(m.lat);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointLLH_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_driver::PointLLH_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_driver::PointLLH_<ContainerAllocator>& v)
  {
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_DRIVER_MESSAGE_POINTLLH_H
