// Generated by gencpp from file gnss_driver/StreamStatus.msg
// DO NOT EDIT!


#ifndef GNSS_DRIVER_MESSAGE_STREAMSTATUS_H
#define GNSS_DRIVER_MESSAGE_STREAMSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gnss_driver
{
template <class ContainerAllocator>
struct StreamStatus_
{
  typedef StreamStatus_<ContainerAllocator> Type;

  StreamStatus_()
    : header()
    , ins_stream_type(0)
    , rtk_stream_in_type(0)
    , rtk_stream_out_type(0)  {
    }
  StreamStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ins_stream_type(0)
    , rtk_stream_in_type(0)
    , rtk_stream_out_type(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _ins_stream_type_type;
  _ins_stream_type_type ins_stream_type;

   typedef uint32_t _rtk_stream_in_type_type;
  _rtk_stream_in_type_type rtk_stream_in_type;

   typedef uint32_t _rtk_stream_out_type_type;
  _rtk_stream_out_type_type rtk_stream_out_type;



  enum {
    DISCONNECTED = 0u,
    CONNECTED = 1u,
  };


  typedef boost::shared_ptr< ::gnss_driver::StreamStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_driver::StreamStatus_<ContainerAllocator> const> ConstPtr;

}; // struct StreamStatus_

typedef ::gnss_driver::StreamStatus_<std::allocator<void> > StreamStatus;

typedef boost::shared_ptr< ::gnss_driver::StreamStatus > StreamStatusPtr;
typedef boost::shared_ptr< ::gnss_driver::StreamStatus const> StreamStatusConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_driver::StreamStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_driver::StreamStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gnss_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'gnss_driver': ['/home/nthom/Documents/ros/rk_node_tutorial/src/gnss_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gnss_driver::StreamStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_driver::StreamStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_driver::StreamStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_driver::StreamStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_driver::StreamStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_driver::StreamStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_driver::StreamStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "684d0fb3e4841d4ebe4b6718a9cbfae6";
  }

  static const char* value(const ::gnss_driver::StreamStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x684d0fb3e4841d4eULL;
  static const uint64_t static_value2 = 0xbe4b6718a9cbfae6ULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_driver::StreamStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_driver/StreamStatus";
  }

  static const char* value(const ::gnss_driver::StreamStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_driver::StreamStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint32 DISCONNECTED=0\n\
uint32 CONNECTED=1\n\
\n\
uint32 ins_stream_type\n\
uint32 rtk_stream_in_type\n\
uint32 rtk_stream_out_type\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::gnss_driver::StreamStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_driver::StreamStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ins_stream_type);
      stream.next(m.rtk_stream_in_type);
      stream.next(m.rtk_stream_out_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StreamStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_driver::StreamStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_driver::StreamStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ins_stream_type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ins_stream_type);
    s << indent << "rtk_stream_in_type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.rtk_stream_in_type);
    s << indent << "rtk_stream_out_type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.rtk_stream_out_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_DRIVER_MESSAGE_STREAMSTATUS_H
