# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gnss_driver/GnssRange.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import gnss_driver.msg
import std_msgs.msg

class GnssRange(genpy.Message):
  _md5sum = "98189513fbb1deb4e990550a5fe42c3d"
  _type = "gnss_driver/GnssRange"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
float64 measurement_time
RangeInfo[] ranges
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: gnss_driver/RangeInfo
int32 GPS=0
int32 GLONASS=1
int32 SBAS=2
int32 GALILEO=3
int32 BEIDOU=4
int32 QZSS=5

int32 constellation
int32 prn

uint32 carrier_frequency
float64 pseudorange
float32 pseudorange_std_dev
float64 carrier_phase
float32 carrier_phase_std_dev
float32 doppler
float32 doppler_std_dev
int32 cno
int32 lock_time
"""
  __slots__ = ['header','measurement_time','ranges']
  _slot_types = ['std_msgs/Header','float64','gnss_driver/RangeInfo[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,measurement_time,ranges

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GnssRange, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.measurement_time is None:
        self.measurement_time = 0.
      if self.ranges is None:
        self.ranges = []
    else:
      self.header = std_msgs.msg.Header()
      self.measurement_time = 0.
      self.ranges = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_d().pack(self.measurement_time))
      length = len(self.ranges)
      buff.write(_struct_I.pack(length))
      for val1 in self.ranges:
        _x = val1
        buff.write(_get_struct_2iIdfd3f2i().pack(_x.constellation, _x.prn, _x.carrier_frequency, _x.pseudorange, _x.pseudorange_std_dev, _x.carrier_phase, _x.carrier_phase_std_dev, _x.doppler, _x.doppler_std_dev, _x.cno, _x.lock_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ranges is None:
        self.ranges = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 8
      (self.measurement_time,) = _get_struct_d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ranges = []
      for i in range(0, length):
        val1 = gnss_driver.msg.RangeInfo()
        _x = val1
        start = end
        end += 52
        (_x.constellation, _x.prn, _x.carrier_frequency, _x.pseudorange, _x.pseudorange_std_dev, _x.carrier_phase, _x.carrier_phase_std_dev, _x.doppler, _x.doppler_std_dev, _x.cno, _x.lock_time,) = _get_struct_2iIdfd3f2i().unpack(str[start:end])
        self.ranges.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_d().pack(self.measurement_time))
      length = len(self.ranges)
      buff.write(_struct_I.pack(length))
      for val1 in self.ranges:
        _x = val1
        buff.write(_get_struct_2iIdfd3f2i().pack(_x.constellation, _x.prn, _x.carrier_frequency, _x.pseudorange, _x.pseudorange_std_dev, _x.carrier_phase, _x.carrier_phase_std_dev, _x.doppler, _x.doppler_std_dev, _x.cno, _x.lock_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ranges is None:
        self.ranges = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 8
      (self.measurement_time,) = _get_struct_d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ranges = []
      for i in range(0, length):
        val1 = gnss_driver.msg.RangeInfo()
        _x = val1
        start = end
        end += 52
        (_x.constellation, _x.prn, _x.carrier_frequency, _x.pseudorange, _x.pseudorange_std_dev, _x.carrier_phase, _x.carrier_phase_std_dev, _x.doppler, _x.doppler_std_dev, _x.cno, _x.lock_time,) = _get_struct_2iIdfd3f2i().unpack(str[start:end])
        self.ranges.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_2iIdfd3f2i = None
def _get_struct_2iIdfd3f2i():
    global _struct_2iIdfd3f2i
    if _struct_2iIdfd3f2i is None:
        _struct_2iIdfd3f2i = struct.Struct("<2iIdfd3f2i")
    return _struct_2iIdfd3f2i
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
