(cl:in-package gnss_driver-msg)
(cl:export '(POSITION-VAL
          POSITION
          ORIENTATION-VAL
          ORIENTATION
          LINEAR_VELOCITY-VAL
          LINEAR_VELOCITY
          LINEAR_ACCELERATION-VAL
          LINEAR_ACCELERATION
          ANGULAR_VELOCITY-VAL
          ANGULAR_VELOCITY
          HEADING-VAL
          HEADING
          LINEAR_ACCELERATION_VRF-VAL
          LINEAR_ACCELERATION_VRF
          ANGULAR_VELOCITY_VRF-VAL
          ANGULAR_VELOCITY_VRF
))