(cl:in-package gnss_driver-msg)
(cl:export '(HEADER-VAL
          HEADER
          MEASUREMENT_TIME-VAL
          MEASUREMENT_TIME
          TYPE-VAL
          TYPE
          POSITION-VAL
          POSITION
          EULER_ANGLES-VAL
          EULER_ANGLES
          LINEAR_VELOCITY-VAL
          LINEAR_VELOCITY
          ANGULAR_VELOCITY-VAL
          ANGULAR_VELOCITY
          LINEAR_ACCELERATION-VAL
          LINEAR_ACCELERATION
          POSITION_COVARIANCE-VAL
          POSITION_COVARIANCE
          EULER_ANGLES_COVARIANCE-VAL
          EULER_ANGLES_COVARIANCE
          LINEAR_VELOCITY_COVARIANCE-VAL
          LINEAR_VELOCITY_COVARIANCE
          ANGULAR_VELOCITY_COVARIANCE-VAL
          ANGULAR_VELOCITY_COVARIANCE
          LINEAR_ACCELERATION_COVARIANCE-VAL
          LINEAR_ACCELERATION_COVARIANCE
))